title: "Pencil2D - opensource animation software"
description: "An easy, intuitive tool to make 2D hand-drawn animations."
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://pencil2d.github.io" # change this to the base hostname & protocol for your site

permalink: /:year/:month/:title.html

google_analytics: UA-5266256-7
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%-d %B, %Y"

#plugins:
#  - jekyll-feed

theme: # leave it empty

# social
author: "Pencil2D"
image: /images/pencil_icon.png

twitter:
  username: pencil2d
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  #app_id: 1798910940422432 # cayman-blog
  authors: pencil2dsoft
  #admins:
github:
  owner_url: "https://github.com/pencil2d/pencil"
  owner_name: "pencil2d"

bitbucket:
  url: "https://bitbucket.org/chchwy/pencil2d"

download:
  win64: https://github.com/pencil2d/pencil/releases/download/0.6.0/pencil2d-win64-0.6.0-ffmpeg341.zip
  win32: https://github.com/pencil2d/pencil/releases/download/0.6.0/pencil2d-win32-0.6.0.zip
  mac: https://github.com/pencil2d/pencil/releases/download/0.6.0/pencil2d-mac-0.6.0.zip
  linux64: https://github.com/pencil2d/pencil/releases/download/0.6.0/pencil2d-linux-amd64-0.6.0.AppImage
  linux32: https://github.com/pencil2d/pencil/releases/download/0.6.0/pencil2d-linux-i386-0.6.0.AppImage
  win64-size: 49.6MB
  win32-size: 43.7MB
  mac-size: 41.7MB
  linux64-size: 37.6MB
  linux32-size: 58.3MB
